sudo: false

language: node_js
node_js:
  - 12
before_install:
  - npm install -i jest
  - npm install -i rimraf
  - npm install -i babel-jest
branches:
  only:
    - master
script:
    - npm test
    - npm run build    
after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
deploy:
  provider: heroku
  api_key: bd4c1f44-1143-45e8-8849-35498252096d
  app: sweetdreamsrucom
  